output file:
processed_pytorch3dse3_exp_map150.json
function:
se3_exp_map
Error Cases:

Pass or Failed: 0

Related Failed Test Cases:
{'FAILED ../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_singularity', 'FAILED ../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_compare_with_precomputed', 'FAILED ../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_to_log_to_exp', 'FAILED ../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_bad_se3_input_value_err', '../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_output_format FAILED', '../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_singularity FAILED', 'FAILED ../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_output_format', 'FAILED ../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_log_to_exp_to_log', 'FAILED ../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_zero_translation', '../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_compare_with_precomputed FAILED', '../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_to_log_to_exp FAILED', '../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_log_to_exp_to_log FAILED', '../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_bad_se3_input_value_err FAILED', '../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_zero_translation FAILED'}

All Test Cases On Generated code:
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-8.3.3, pluggy-1.5.0 -- /local/data0/moved_data/pytorch3d/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/pytorch3d
collecting ... collected 9 items

../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_bad_se3_input_value_err FAILED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_compare_with_precomputed FAILED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_output_format FAILED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_singularity FAILED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_to_log_to_exp FAILED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_zero_translation FAILED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_log_singularity PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_log_to_exp_to_log FAILED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_log_zero_translation PASSED

=================================== FAILURES ===================================
_____________________ TestSE3.test_bad_se3_input_value_err _____________________

self = <tests.test_se3.TestSE3 testMethod=test_bad_se3_input_value_err>

    def test_bad_se3_input_value_err(self):
        """
        Tests whether `se3_exp_map` and `se3_log_map` correctly return
        a ValueError if called with an argument of incorrect shape, or with
        an tensor containing illegal values.
        """
        device = torch.device("cuda:0")
    
        for size in ([5, 4], [3, 4, 5], [3, 5, 6]):
            log_transform = torch.randn(size=size, device=device)
            with self.assertRaises(ValueError):
>               se3_exp_map(log_transform)

/local/data0/moved_data/pytorch3d/tests/test_se3.py:293: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def se3_exp_map(log_transform: torch.Tensor, eps: float=0.0001) -> torch.Tensor:
>       from .temp import se3_exp_map
E       ImportError: cannot import name 'se3_exp_map' from 'pytorch3d.transforms.temp' (/local/data0/moved_data/pytorch3d/pytorch3d/transforms/temp.py)

/local/data0/moved_data/pytorch3d/pytorch3d/transforms/se3.py:5: ImportError
____________________ TestSE3.test_compare_with_precomputed _____________________

self = <tests.test_se3.TestSE3 testMethod=test_compare_with_precomputed>

    def test_compare_with_precomputed(self):
        """
        Compare the outputs against precomputed results.
        """
        self.assertClose(
            se3_log_map(self.precomputed_transform),
            self.precomputed_log_transform,
            atol=1e-4,
        )
        self.assertClose(
            self.precomputed_transform,
>           se3_exp_map(self.precomputed_log_transform),
            atol=1e-4,
        )

/local/data0/moved_data/pytorch3d/tests/test_se3.py:165: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

log_transform = tensor([[ 0.1900,  2.1600, -0.1700,  0.8500, -1.9200,  0.6500],
        [-0.6500, -0.8200,  0.5300, -1.2800, -1.6600, ...-0.3300, -0.5300, -0.8800,  0.3900,  0.1600, -0.2000],
        [ 1.0100, -1.3500, -0.3500, -0.6400,  0.4500, -0.5400]])
eps = 0.0001

    def se3_exp_map(log_transform: torch.Tensor, eps: float=0.0001) -> torch.Tensor:
>       from .temp import se3_exp_map
E       ImportError: cannot import name 'se3_exp_map' from 'pytorch3d.transforms.temp' (/local/data0/moved_data/pytorch3d/pytorch3d/transforms/temp.py)

/local/data0/moved_data/pytorch3d/pytorch3d/transforms/se3.py:5: ImportError
______________________ TestSE3.test_se3_exp_output_format ______________________

self = <tests.test_se3.TestSE3 testMethod=test_se3_exp_output_format>
batch_size = 100

    def test_se3_exp_output_format(self, batch_size: int = 100):
        """
        Check that the output of `se3_exp_map` is a valid SE3 matrix.
        """
>       transform = se3_exp_map(TestSE3.init_log_transform(batch_size=batch_size))

/local/data0/moved_data/pytorch3d/tests/test_se3.py:137: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

log_transform = tensor([[ 1.9402e-01,  2.1614e+00, -1.7205e-01,  8.4906e-01, -1.9244e+00,
          6.5299e-01],
        [-6.4944e-01,...01],
        [-3.6217e-01, -5.8366e-01, -1.7007e+00,  3.6993e-01,  7.4330e-01,
         -1.1991e-01]], device='cuda:0')
eps = 0.0001

    def se3_exp_map(log_transform: torch.Tensor, eps: float=0.0001) -> torch.Tensor:
>       from .temp import se3_exp_map
E       ImportError: cannot import name 'se3_exp_map' from 'pytorch3d.transforms.temp' (/local/data0/moved_data/pytorch3d/pytorch3d/transforms/temp.py)

/local/data0/moved_data/pytorch3d/pytorch3d/transforms/se3.py:5: ImportError
_______________________ TestSE3.test_se3_exp_singularity _______________________

self = <tests.test_se3.TestSE3 testMethod=test_se3_exp_singularity>
batch_size = 100

    def test_se3_exp_singularity(self, batch_size: int = 100):
        """
        Tests whether the `se3_exp_map` is robust to the input vectors
        with low L2 norms, where the algorithm is numerically unstable.
        """
        # generate random log-rotations with a tiny angle
        log_rot = TestSE3.init_log_transform(batch_size=batch_size)
        log_rot_small = log_rot * 1e-6
        log_rot_small.requires_grad = True
>       transforms = se3_exp_map(log_rot_small)

/local/data0/moved_data/pytorch3d/tests/test_se3.py:178: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

log_transform = tensor([[ 1.9402e-07,  2.1614e-06, -1.7205e-07,  8.4906e-07, -1.9244e-06,
          6.5299e-07],
        [-6.4944e-07,...7e-07, -5.8366e-07, -1.7007e-06,  3.6993e-07,  7.4330e-07,
         -1.1991e-07]], device='cuda:0', requires_grad=True)
eps = 0.0001

    def se3_exp_map(log_transform: torch.Tensor, eps: float=0.0001) -> torch.Tensor:
>       from .temp import se3_exp_map
E       ImportError: cannot import name 'se3_exp_map' from 'pytorch3d.transforms.temp' (/local/data0/moved_data/pytorch3d/pytorch3d/transforms/temp.py)

/local/data0/moved_data/pytorch3d/pytorch3d/transforms/se3.py:5: ImportError
______________________ TestSE3.test_se3_exp_to_log_to_exp ______________________

self = <tests.test_se3.TestSE3 testMethod=test_se3_exp_to_log_to_exp>
batch_size = 10000

    def test_se3_exp_to_log_to_exp(self, batch_size: int = 10000):
        """
        Check that `se3_exp_map(se3_log_map(A))==A` for
        a batch of randomly generated SE(3) matrices `A`.
        """
        transform = TestSE3.init_transform(batch_size=batch_size)
        # Limit test transforms to those not around the singularity where
        # the rotation angle~=pi.
        nonsingular = so3_rotation_angle(transform[:, :3, :3]) < 3.134
        transform = transform[nonsingular]
>       transform_ = se3_exp_map(
            se3_log_map(transform, eps=1e-8, cos_bound=0.0), eps=1e-8
        )

/local/data0/moved_data/pytorch3d/tests/test_se3.py:268: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

log_transform = tensor([[ 0.0536,  1.0608, -0.2628, -2.7617,  0.2198, -1.0849],
        [ 0.2821,  0.2623, -1.2972,  0.6037, -0.6004, ...8, -0.7656,  0.6934,  0.8629],
        [-1.6430,  2.2158,  0.5445,  1.3354, -0.8682, -2.2528]],
       device='cuda:0')
eps = 1e-08

    def se3_exp_map(log_transform: torch.Tensor, eps: float=0.0001) -> torch.Tensor:
>       from .temp import se3_exp_map
E       ImportError: cannot import name 'se3_exp_map' from 'pytorch3d.transforms.temp' (/local/data0/moved_data/pytorch3d/pytorch3d/transforms/temp.py)

/local/data0/moved_data/pytorch3d/pytorch3d/transforms/se3.py:5: ImportError
____________________ TestSE3.test_se3_exp_zero_translation _____________________

self = <tests.test_se3.TestSE3 testMethod=test_se3_exp_zero_translation>
batch_size = 100

    def test_se3_exp_zero_translation(self, batch_size: int = 100):
        """
        Check that `se3_exp_map` with zero translation gives
        the same result as corresponding `so3_exp_map`.
        """
        log_transform = TestSE3.init_log_transform(batch_size=batch_size)
        log_transform[:, :3] *= 0.0
>       transform = se3_exp_map(log_transform, eps=1e-8)

/local/data0/moved_data/pytorch3d/tests/test_se3.py:235: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

log_transform = tensor([[ 0.0000e+00,  0.0000e+00, -0.0000e+00,  8.4906e-01, -1.9244e+00,
          6.5299e-01],
        [-0.0000e+00,...01],
        [-0.0000e+00, -0.0000e+00, -0.0000e+00,  3.6993e-01,  7.4330e-01,
         -1.1991e-01]], device='cuda:0')
eps = 1e-08

    def se3_exp_map(log_transform: torch.Tensor, eps: float=0.0001) -> torch.Tensor:
>       from .temp import se3_exp_map
E       ImportError: cannot import name 'se3_exp_map' from 'pytorch3d.transforms.temp' (/local/data0/moved_data/pytorch3d/pytorch3d/transforms/temp.py)

/local/data0/moved_data/pytorch3d/pytorch3d/transforms/se3.py:5: ImportError
______________________ TestSE3.test_se3_log_to_exp_to_log ______________________

self = <tests.test_se3.TestSE3 testMethod=test_se3_log_to_exp_to_log>
batch_size = 100

    def test_se3_log_to_exp_to_log(self, batch_size: int = 100):
        """
        Check that `se3_log_map(se3_exp_map(log_transform))==log_transform`
        for a randomly generated batch of SE(3) matrix logarithms `log_transform`.
        """
        log_transform = TestSE3.init_log_transform(batch_size=batch_size)
>       log_transform_ = se3_log_map(se3_exp_map(log_transform, eps=1e-8), eps=1e-8)

/local/data0/moved_data/pytorch3d/tests/test_se3.py:279: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

log_transform = tensor([[ 1.9402e-01,  2.1614e+00, -1.7205e-01,  8.4906e-01, -1.9244e+00,
          6.5299e-01],
        [-6.4944e-01,...01],
        [-3.6217e-01, -5.8366e-01, -1.7007e+00,  3.6993e-01,  7.4330e-01,
         -1.1991e-01]], device='cuda:0')
eps = 1e-08

    def se3_exp_map(log_transform: torch.Tensor, eps: float=0.0001) -> torch.Tensor:
>       from .temp import se3_exp_map
E       ImportError: cannot import name 'se3_exp_map' from 'pytorch3d.transforms.temp' (/local/data0/moved_data/pytorch3d/pytorch3d/transforms/temp.py)

/local/data0/moved_data/pytorch3d/pytorch3d/transforms/se3.py:5: ImportError
=========================== short test summary info ============================
FAILED ../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_bad_se3_input_value_err
FAILED ../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_compare_with_precomputed
FAILED ../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_output_format
FAILED ../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_singularity
FAILED ../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_to_log_to_exp
FAILED ../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_zero_translation
FAILED ../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_log_to_exp_to_log
========================= 7 failed, 2 passed in 1.53s ==========================


Final Test Result:
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-8.3.3, pluggy-1.5.0 -- /local/data0/moved_data/pytorch3d/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/pytorch3d
collecting ... collected 9 items

../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_bad_se3_input_value_err PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_compare_with_precomputed PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_output_format PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_singularity PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_to_log_to_exp PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_zero_translation PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_log_singularity PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_log_to_exp_to_log PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_log_zero_translation PASSED

============================== 9 passed in 1.41s ===============================


Initial Result:
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-8.3.3, pluggy-1.5.0 -- /local/data0/moved_data/pytorch3d/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/pytorch3d
collecting ... collected 9 items

../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_bad_se3_input_value_err PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_compare_with_precomputed PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_output_format PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_singularity PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_to_log_to_exp PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_exp_zero_translation PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_log_singularity PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_log_to_exp_to_log PASSED
../../../../../../local/data0/moved_data/pytorch3d/tests/test_se3.py::TestSE3::test_se3_log_zero_translation PASSED

============================== 9 passed in 1.56s ===============================
