output file:
processed_visionpil_to_tensor191.json
function:
pil_to_tensor
Error Cases:

Pass or Failed: 0

Related Failed Test Cases:
{'../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[1] FAILED', 'FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[3]', '../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[4] FAILED', '../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[3] FAILED', 'FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[1]', 'FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[4]'}

All Test Cases On Generated code:
============================= test session starts ==============================
platform linux -- Python 3.11.10, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/vision/vision/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/vision/vision
configfile: pytest.ini
plugins: mock-3.14.0
collecting ... collected 3 items

../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[1] FAILED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[3] FAILED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[4] FAILED

=================================== FAILURES ===================================
______________________ TestToTensor.test_pil_to_tensor[1] ______________________
/local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py:276: in test_pil_to_tensor
    torch.testing.assert_close(input_data, output)
E   AssertionError: The values for attribute 'shape' do not match: torch.Size([1, 4, 4]) != torch.Size([4, 4]).
______________________ TestToTensor.test_pil_to_tensor[3] ______________________
/local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py:294: in test_pil_to_tensor
    torch.testing.assert_close(input_data, output)
E   AssertionError: The values for attribute 'shape' do not match: torch.Size([1, 4, 4]) != torch.Size([4, 4]).
______________________ TestToTensor.test_pil_to_tensor[4] ______________________
/local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py:276: in test_pil_to_tensor
    torch.testing.assert_close(input_data, output)
E   AssertionError: Tensor-likes are not equal!
E   
E   Mismatched elements: 60 / 64 (93.8%)
E   Greatest absolute difference: 175 at index (3, 1, 1)
E   Greatest relative difference: 10.266666412353516 at index (3, 0, 1)
=========================== short test summary info ============================
FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[1]
FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[3]
FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[4]
============================== 3 failed in 0.65s ===============================


Final Test Result:
============================= test session starts ==============================
platform linux -- Python 3.11.10, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/vision/vision/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/vision/vision
configfile: pytest.ini
plugins: mock-3.14.0
collecting ... collected 3 items

../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[1] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[3] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[4] PASSED

============================== 3 passed in 0.45s ===============================


Initial Result:
============================= test session starts ==============================
platform linux -- Python 3.11.10, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/vision/vision/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/vision/vision
configfile: pytest.ini
plugins: mock-3.14.0
collecting ... collected 3 items

../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[1] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[3] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[4] PASSED

============================== 3 passed in 2.45s ===============================
