output file:
processed_visionto_pil_image152.json
function:
to_pil_image
Error Cases:

Pass or Failed: 0

Related Failed Test Cases:
{'FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[3]', '../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[4] FAILED', '../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[3] FAILED', '../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[1] FAILED', '../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[3] FAILED', 'FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[1]', '../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[4] FAILED', 'FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[4]', 'FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[3]', '../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[1] FAILED', 'FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[1]', 'FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[4]'}

All Test Cases On Generated code:
============================= test session starts ==============================
platform linux -- Python 3.11.10, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/vision/vision/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/vision/vision
configfile: pytest.ini
plugins: mock-3.14.0
collecting ... collected 11 items

../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[1] FAILED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[3] FAILED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[4] FAILED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor_errors PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor_with_other_default_dtypes[dtype0] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor_with_other_default_dtypes[dtype1] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor_with_other_default_dtypes[dtype2] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[1] FAILED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[3] FAILED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[4] FAILED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor_errors PASSED

=================================== FAILURES ===================================
________________________ TestToTensor.test_to_tensor[1] ________________________
/local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py:218: in test_to_tensor
    img = transforms.ToPILImage()(input_data)
/local/data0/moved_data/publishablew/vision/vision/torchvision/transforms/transforms.py:234: in __call__
    return F.to_pil_image(pic, self.mode)
/local/data0/moved_data/publishablew/vision/vision/torchvision/transforms/functional.py:192: in to_pil_image
    return to_pil_image(pic, mode)
/local/data0/moved_data/publishablew/vision/vision/torchvision/transforms/temp.py:58: in to_pil_image
    raise TypeError(f'Unsupported data type: {pic.dtype}')
E   TypeError: Unsupported data type: float32
________________________ TestToTensor.test_to_tensor[3] ________________________
/local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py:218: in test_to_tensor
    img = transforms.ToPILImage()(input_data)
/local/data0/moved_data/publishablew/vision/vision/torchvision/transforms/transforms.py:234: in __call__
    return F.to_pil_image(pic, self.mode)
/local/data0/moved_data/publishablew/vision/vision/torchvision/transforms/functional.py:192: in to_pil_image
    return to_pil_image(pic, mode)
/local/data0/moved_data/publishablew/vision/vision/torchvision/transforms/temp.py:58: in to_pil_image
    raise TypeError(f'Unsupported data type: {pic.dtype}')
E   TypeError: Unsupported data type: float32
________________________ TestToTensor.test_to_tensor[4] ________________________
/local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py:218: in test_to_tensor
    img = transforms.ToPILImage()(input_data)
/local/data0/moved_data/publishablew/vision/vision/torchvision/transforms/transforms.py:234: in __call__
    return F.to_pil_image(pic, self.mode)
/local/data0/moved_data/publishablew/vision/vision/torchvision/transforms/functional.py:192: in to_pil_image
    return to_pil_image(pic, mode)
/local/data0/moved_data/publishablew/vision/vision/torchvision/transforms/temp.py:58: in to_pil_image
    raise TypeError(f'Unsupported data type: {pic.dtype}')
E   TypeError: Unsupported data type: float32
______________________ TestToTensor.test_pil_to_tensor[1] ______________________
/local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py:282: in test_pil_to_tensor
    torch.testing.assert_close(output.numpy(), expected_output)
E   AssertionError: The values for attribute 'shape' do not match: torch.Size([4, 4, 1]) != torch.Size([1, 4, 4]).
______________________ TestToTensor.test_pil_to_tensor[3] ______________________
/local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py:282: in test_pil_to_tensor
    torch.testing.assert_close(output.numpy(), expected_output)
E   AssertionError: The values for attribute 'shape' do not match: torch.Size([4, 4, 3]) != torch.Size([3, 4, 4]).
______________________ TestToTensor.test_pil_to_tensor[4] ______________________
/local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py:282: in test_pil_to_tensor
    torch.testing.assert_close(output.numpy(), expected_output)
E   AssertionError: Tensor-likes are not equal!
E   
E   Mismatched elements: 60 / 64 (93.8%)
E   Greatest absolute difference: 222 at index (2, 0, 2)
E   Greatest relative difference: 20.33333396911621 at index (2, 1, 3)
=========================== short test summary info ============================
FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[1]
FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[3]
FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[4]
FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[1]
FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[3]
FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[4]
========================= 6 failed, 5 passed in 0.88s ==========================


Final Test Result:
============================= test session starts ==============================
platform linux -- Python 3.11.10, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/vision/vision/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/vision/vision
configfile: pytest.ini
plugins: mock-3.14.0
collecting ... collected 11 items

../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[1] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[3] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[4] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor_errors PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor_with_other_default_dtypes[dtype0] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor_with_other_default_dtypes[dtype1] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor_with_other_default_dtypes[dtype2] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[1] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[3] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[4] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor_errors PASSED

============================== 11 passed in 0.44s ==============================


Initial Result:
============================= test session starts ==============================
platform linux -- Python 3.11.10, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/vision/vision/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/vision/vision
configfile: pytest.ini
plugins: mock-3.14.0
collecting ... collected 11 items

../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[1] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[3] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor[4] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor_errors PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor_with_other_default_dtypes[dtype0] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor_with_other_default_dtypes[dtype1] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_to_tensor_with_other_default_dtypes[dtype2] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[1] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[3] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor[4] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_transforms.py::TestToTensor::test_pil_to_tensor_errors PASSED

============================== 11 passed in 0.45s ==============================
